_target_: src.module.KDResNetModule

model_conf:
  name: resnet18
  resnet_version: 18
  num_classes: 10
  pre_train: True
  tune_only_fc: False
  teacher_model_name: resnet50
  teacher_model_path: data/cifar10/resnet18.pt
  teacher_lambda: 0.05
  temperature: 10
  

optimizer_conf:
  name: SGD
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0005

criterion_conf:
  name: CE