_target_: src.module.SelfKDResNetModule

model_conf:
  name: resnet18
  resnet_version: 18
  num_classes: 100
  pre_train: True
  tune_only_fc: False
  self_alpha: 0.1
  self_beta: 1e-6
  temperature: 3
  
optimizer_conf:
  name: SGD
  lr: 1e-3
  momentum: 0.9
  weight_decay: 5e-4
  use_cosine_anneal: True
  anneal_T0: 30
  anneal_max: 0.1
  anneal_gamma: 0.5

criterion_conf:
  name: CE
  use_mixup: True
  mixup_alpha: 0.4