defaults:
  - modules: resnet18.yaml
  - datamodules: cifar100.yaml
  - trainer: default.yaml
  - callbacks:
      - modelcheckpoint.yaml
      - learninglatemonitor.yaml
  - hydra: default.yaml

seed: 42
work_dir: ${hydra:runtime.cwd}
time: ${now:%Y-%m-%d_%H-%M-%S}