defaults:
  - modules: resnet18.yaml
  - datamodules: cifar10.yaml
  - trainer: default.yaml
  - callbacks:
      - modelcheckpoint.yaml

seed: 42
work_dir: ${hydra:runtime.cwd}
default_path: logs/${modules.model_conf.name}/${datamodules.dataset_conf.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}